---
# cofigure ansible engine and nodes with users and access

- hosts: all
  become: true
  tasks:
    - name: Set Hostname
      hostname:
        name: "{{ inventory_hostname }}"

    #- name: Install Packages
    #  yum:
    #    name:
    #      - vim
    #    state: present
  
    - name: Create .ssh if not exist
      file:
        path: /home/devops/.ssh
        state: directory
        owner: devops
        group: devops
        mode: 0700

    - name: Create authorized_keys if not exist
      copy:
        dest: /home/devops/.ssh/authorized_keys
        content: ""
        force: no
        owner: devops 
        group: devops
        mode: '0600'

    - name: Copy Authorized keys to devops user
      blockinfile:
        path: /home/devops/.ssh/authorized_keys
        block:  "{{ lookup('file', '/home/ec2-user/.ssh/authorized_keys') 
}}"
    - name: Copy Sample Inventory to devops home
      copy:
        src: '/home/ec2-user/inventory'
        dest: "/home/devops/inventory"
        mode: '0755'
        owner: devops
        group: devops
      when: inventory_hostname == 'ansible-engine'

    - name: Copy ansible.cfg to devops home
      copy:
        src: '/home/ec2-user/ansible.cfg'
        dest: "/home/devops/ansible.cfg"
        mode: '0755'
        owner: devops
        group: devops
      when: inventory_hostname == 'ansible-engine'

    - name: Update /etc/hosts
      lineinfile:
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}"
        path: /etc/hosts
      loop: "{{ groups['all'] }}"